import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { NavSearch } from "@/components/navSearch";
import { UserAvatar } from "@/components/userAvatar";
import { ThemeProvider } from "@/providers/themeProvider";
import { NewTransaction } from "@/components/newTransaction";
import { Button } from "@/components/ui/button";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <main className="flex flex-col">
            {/* navbar */}
            <div className="border-b">
              <div className="flex h-16 items-center px-4">
                {/* <TeamSwitcher /> */}
                <Navbar className="mx-6" />
                <div className="ml-auto flex items-center space-x-4">
                  <NavSearch />
                  <UserAvatar />
                </div>
              </div>
            </div>

            <div className="flex-1 space-y-4 p-8 pt-6">
              {children}
            </div>

            <NewTransaction
              trigger={
                <div className="fixed bottom-8 right-8">
                <Button className="rounded-full w-14 h-14" >
                  <span className="text-4xl">+</span>
                </Button>
              </div>
              }
            />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
